-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 23:10:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema R00145347 - Dominic M Brause
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema R00145347
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `R00145347` DEFAULT CHARACTER SET utf8 ;
USE `R00145347` ;

-- -----------------------------------------------------
-- Table `R00145347`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `R00145347`.`Branch` (
  `idBranch` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  PRIMARY KEY (`idBranch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `R00145347`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `R00145347`.`Staff` (
  `idStaff` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  `Branch_idBranch` INT NOT NULL,
  PRIMARY KEY (`idStaff`, `Branch_idBranch`),
  INDEX `fk_Staff_Branch_idx` (`Branch_idBranch` ASC),
  CONSTRAINT `fk_Staff_Branch`
    FOREIGN KEY (`Branch_idBranch`)
    REFERENCES `R00145347`.`Branch` (`idBranch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `R00145347`.`PrivateOwner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `R00145347`.`PrivateOwner` (
  `idPrivateOwner` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrivateOwner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `R00145347`.`PropertyToRent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `R00145347`.`PropertyToRent` (
  `idPropertyToRent` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  `Staff_idStaff` INT NOT NULL,
  `Staff_Branch_idBranch` INT NOT NULL,
  `PrivateOwner_idPrivateOwner` INT NOT NULL,
  PRIMARY KEY (`idPropertyToRent`, `Staff_idStaff`, `Staff_Branch_idBranch`, `PrivateOwner_idPrivateOwner`),
  INDEX `fk_PropertyToRent_Staff1_idx` (`Staff_idStaff` ASC, `Staff_Branch_idBranch` ASC),
  INDEX `fk_PropertyToRent_PrivateOwner1_idx` (`PrivateOwner_idPrivateOwner` ASC),
  CONSTRAINT `fk_PropertyToRent_Staff1`
    FOREIGN KEY (`Staff_idStaff` , `Staff_Branch_idBranch`)
    REFERENCES `R00145347`.`Staff` (`idStaff` , `Branch_idBranch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PropertyToRent_PrivateOwner1`
    FOREIGN KEY (`PrivateOwner_idPrivateOwner`)
    REFERENCES `R00145347`.`PrivateOwner` (`idPrivateOwner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `R00145347`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `R00145347`.`Client` (
  `idClient` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `preferredType` VARCHAR(45) NULL,
  `maxRent` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `R00145347`.`Viewing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `R00145347`.`Viewing` (
  `Client_idClient` INT NOT NULL,
  `PropertyToRent_idPropertyToRent` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`Client_idClient`, `PropertyToRent_idPropertyToRent`),
  INDEX `fk_Viewing_PropertyToRent1_idx` (`PropertyToRent_idPropertyToRent` ASC),
  CONSTRAINT `fk_Viewing_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `R00145347`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viewing_PropertyToRent1`
    FOREIGN KEY (`PropertyToRent_idPropertyToRent`)
    REFERENCES `R00145347`.`PropertyToRent` (`idPropertyToRent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
